name: iosApp
options:
  bundleIdPrefix: com.notemusicali
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"

settings:
  base:
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"

targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
    settings:
      base:
        INFOPLIST_FILE: iosApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.notemusicali.iosApp
        PRODUCT_NAME: InTono
        DEVELOPMENT_TEAM: X4PCY86YL9
        CODE_SIGN_STYLE: Automatic
        FRAMEWORK_SEARCH_PATHS:
          - "$(inherited)"
          - "$(SRCROOT)/../shared/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)"
        OTHER_LINKER_FLAGS:
          - "$(inherited)"
          - "-ObjC"
          - "-framework"
          - "shared"
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    preBuildScripts:
      - name: "Compile Kotlin Framework"
        script: |
          cd "$SRCROOT/.."
          ./gradlew :shared:embedAndSignAppleFrameworkForXcode
        basedOnDependencyAnalysis: false
